In [0]:
import pandas as pd
import numpy as np

In [0]:
def sido_name(data):
    data['area'] == '광주'

In [0]:
makingcost = pd.read_excel('../projectdata/onion_making_cost.xls')
makingcost

,year,생산비 합계,직접생산비,종묘비,비료비,농약비,기타 재료비,수도광열비,농구비,영농시설비,자동차비,노동비,위탁영농비,기타비용,생산관리비,간접생산비,토지용역비,자본용역비,부산물생산비,부산물공제생산비
0,1991_강원도,627287,483475,26474,75832,8544,15887,1121,18378,1565,0,335674,0,0,0,143812,114377,29435,598,626689
1,1991_경기도,627287,483475,26474,75832,8544,15887,1121,18378,1565,0,335674,0,0,0,143812,114377,29435,598,626689
2,1991_경상남도,627287,483475,26474,75832,8544,15887,1121,18378,1565,0,335674,0,0,0,143812,114377,29435,598,626689
3,1991_경상북도,627287,483475,26474,75832,8544,15887,1121,18378,1565,0,335674,0,0,0,143812,114377,29435,598,626689
4,1991_광주,627287,483475,26474,75832,8544,15887,1121,18378,1565,0,335674,0,0,0,143812,114377,29435,598,626689
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,2019_전라남도,2533348,2304559,240134,257493,127549,69943,7378,20032,4634,9018,1369916,150036,48029,398,228789,195603,33186,530,2532818
460,2019_전라북도,2533348,2304559,240134,257493,127549,69943,7378,20032,4634,9018,1369916,150036,48029,398,228789,195603,33186,530,2532818
461,2019_제주특별자치도,2533348,2304559,240134,257493,127549,69943,7378,20032,4634,9018,1369916,150036,48029,398,228789,195603,33186,530,2532818
462,2019_충청남도,2533348,2304559,240134,257493,127549,69943,7378,20032,4634,9018,1369916,150036,48029,398,228789,195603,33186,530,2532818
463,2019_충청북도,2533348,2304559,240134,257493,127549,69943,7378,20032,4634,9018,1369916,150036,48029,398,228789,195603,33186,530,2532818

In [0]:
def year_area(data):
    year = []
    area = []
    for i in data['year']:
        year.append(i[:4])
        area.append(i[5:])
    data['year'] = pd.Series(year)
    data['area'] = pd.Series(area)

In [0]:
year_area(makingcost)
makingcost

,year,생산비 합계,직접생산비,종묘비,비료비,농약비,기타 재료비,수도광열비,농구비,영농시설비,...,노동비,위탁영농비,기타비용,생산관리비,간접생산비,토지용역비,자본용역비,부산물생산비,부산물공제생산비,area
0,1991,627287,483475,26474,75832,8544,15887,1121,18378,1565,...,335674,0,0,0,143812,114377,29435,598,626689,강원도
1,1991,627287,483475,26474,75832,8544,15887,1121,18378,1565,...,335674,0,0,0,143812,114377,29435,598,626689,경기도
2,1991,627287,483475,26474,75832,8544,15887,1121,18378,1565,...,335674,0,0,0,143812,114377,29435,598,626689,경상남도
3,1991,627287,483475,26474,75832,8544,15887,1121,18378,1565,...,335674,0,0,0,143812,114377,29435,598,626689,경상북도
4,1991,627287,483475,26474,75832,8544,15887,1121,18378,1565,...,335674,0,0,0,143812,114377,29435,598,626689,광주
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,2019,2533348,2304559,240134,257493,127549,69943,7378,20032,4634,...,1369916,150036,48029,398,228789,195603,33186,530,2532818,전라남도
460,2019,2533348,2304559,240134,257493,127549,69943,7378,20032,4634,...,1369916,150036,48029,398,228789,195603,33186,530,2532818,전라북도
461,2019,2533348,2304559,240134,257493,127549,69943,7378,20032,4634,...,1369916,150036,48029,398,228789,195603,33186,530,2532818,제주특별자치도
462,2019,2533348,2304559,240134,257493,127549,69943,7378,20032,4634,...,1369916,150036,48029,398,228789,195603,33186,530,2532818,충청남도
463,2019,2533348,2304559,240134,257493,127549,69943,7378,20032,4634,...,1369916,150036,48029,398,228789,195603,33186,530,2532818,충청북도

In [0]:
makingcost.area.unique()

array(['강원도', '경기도', '경상남도', '경상북도', '광주', '대구', '대전', '부산', '서울', '울산',
       '인천', '전라남도', '전라북도', '제주특별자치도', '충청남도', '충청북도'], dtype=object)

In [0]:
def sido_name(df):
    df['area'] = df['area'].apply(lambda x: '광주광역시' if '광주' in x
                                    else('인천광역시' if '인천' in x
                                    else('부산광역시' if '부산' in x
                                    else('대전광역시' if '대전' in x
                                    else('대구광역시' if '대구' in x
                                    else('서울특별시' if '서울' in x
                                    else('울산광역시' if '울산' in x
                                    else('제주도' if '제주' in x
                                    else x))))))))

In [0]:
sido_name(makingcost)

In [0]:
makingcost

,year,생산비 합계,직접생산비,종묘비,비료비,농약비,기타 재료비,수도광열비,농구비,영농시설비,...,노동비,위탁영농비,기타비용,생산관리비,간접생산비,토지용역비,자본용역비,부산물생산비,부산물공제생산비,area
0,1991,627287,483475,26474,75832,8544,15887,1121,18378,1565,...,335674,0,0,0,143812,114377,29435,598,626689,강원도
1,1991,627287,483475,26474,75832,8544,15887,1121,18378,1565,...,335674,0,0,0,143812,114377,29435,598,626689,경기도
2,1991,627287,483475,26474,75832,8544,15887,1121,18378,1565,...,335674,0,0,0,143812,114377,29435,598,626689,경상남도
3,1991,627287,483475,26474,75832,8544,15887,1121,18378,1565,...,335674,0,0,0,143812,114377,29435,598,626689,경상북도
4,1991,627287,483475,26474,75832,8544,15887,1121,18378,1565,...,335674,0,0,0,143812,114377,29435,598,626689,광주광역시
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,2019,2533348,2304559,240134,257493,127549,69943,7378,20032,4634,...,1369916,150036,48029,398,228789,195603,33186,530,2532818,전라남도
460,2019,2533348,2304559,240134,257493,127549,69943,7378,20032,4634,...,1369916,150036,48029,398,228789,195603,33186,530,2532818,전라북도
461,2019,2533348,2304559,240134,257493,127549,69943,7378,20032,4634,...,1369916,150036,48029,398,228789,195603,33186,530,2532818,제주도
462,2019,2533348,2304559,240134,257493,127549,69943,7378,20032,4634,...,1369916,150036,48029,398,228789,195603,33186,530,2532818,충청남도
463,2019,2533348,2304559,240134,257493,127549,69943,7378,20032,4634,...,1369916,150036,48029,398,228789,195603,33186,530,2532818,충청북도

In [0]:
makingcost.to_csv('../projectdata/onion_price.csv')